version: "3"
services:
  db:
    image: mysql:latest
    container_name: local-mysql-fast-campus
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secretpassword
      - MYSQL_DATABASE=fastcampus
    volumes:
      - /Users/hilmiikhsan/go/src/fast-campus-project/fastcampus_mysql/db:/var/lib/mysql