CREATE TABLE IF NOT EXISTS posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    post_title VARCHAR(255) NOT NULL,
    post_content LONGTEXT NOT NULL,
    post_hashtags LONGTEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by LONGTEXT NOT NULL,
    updated_by LONGTEXT NOT NULL,

   CONSTRAINT fk_user_id_posts FOREIGN KEY (user_id) REFERENCES users(id)
)